#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
_ = lambda __ : __import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(__[::-1])));exec((_)(b'==AwUvFTX1/S+9R9G+v/fG+9232/N9nZ87z/n3/vV/xPPfO+/fr+D+J/+/3T6Pm/Y+/D4//Dzv//rrv//Ob//M9v+kN/+L2d3+/n1vp/Sd8PM1zfLy/vm//3fx+/vk/ff/90+/3d+//6//b+Xm3Q//d79/14KZV/P+dNBBBllsjMrMqC07/U26DblWtZTJvQRrDvKra/UsWCaE2Q+uWkj6mcH6dbD+Kk1bEbiqoMKn1iXEnZMmhmTtBrIoBUIQhWEUVgoCi2I5i0IcipwYxnwBmk2826/a4u6D2gCWhgASQno1jVMRfgJxRy5DbQC4d0DIAcV2dg3nE10bWOJb6Hsy+mxx2jKuEnT7Yv8ffMINbP1/OT6vhCANjJv6rSWPnoVWZQUvkOUvvIyMuKcNfcE6tcLXF2UP6jK2usnOFmX7s46DTrWDFr2HdcJtjAWPpAGusise3pPwlQDD3mix0mlZ1nlzFBA5eJ5y5HfhTsjYqCjh8Gv8ZS7RR5+nF+Yq4ZZBzK9mrHskp7O3Sr+MZ9wqKsVrrMymKtmKJAeFIJz2QYVCcaUeLhTSYhFCtzg39yh+R1eIou7qVdz/BTIyG8J+RPVV3U6La6/jjIcE+aHXhN9kUzd25V1ORYYxgb6izLjoDSBZp4yHXvJllL3O9ObQZOmFJGKDsU24Bf5q4YggVTGf38dVNJnpzioQO5g0A67tOADq1f/QnZGqoRw4jXS8BDRcp6/44Y5U3HBUyqpcPFaJ5QQVcsKtntEuvPc5VPIQLlKG7sKp7U1Mkz0tTq7RnBRs9zWenbL6n554Pvl8i95mEN8pIEEYko7nsLYgf5A7Xb7riy5EUfRRBduuhnneeSZ2kgFuKGSV0w8fxAsy1Nug5ASslcDbZcRWi2tczZlD7bZNikctxGlwDoWVpWdR8V9Cr7Fb8KZ9MNVn2o5rn50pTMo1yKdJFy0tG4OXdsNcmUHv3eOkG0DEXGXhjZx8hK2X5m2/C7GXzVbjQ4MIGbzvPrlgUTfmwZrmg+lUL577z6ht8okBcDvJ3+hSGO8BFgbPL69JQeCOJ6U1goPWRsSV2Uf7ynqiJBnH9bLItbeRGzI1i01OAiPeUEevE4jzQII8eG29Lf6hJd+Awkr4EdK86i5Uqp/pMQMXfRi19AhXem4Es8I0xWhl/qLHJDjyH/wb0fDzsOCTZDz5EnEOdQEWi7Obn0VP49sYDvjmX6dofI8y4TuLEN50F5RyD6GWDykAVQG5L87AQczUzzkfEnu/neUhx1hrbKiGscVi94f0bs0cGyPTIEzloif0M6PO51KIIVXymDhc4ENKgl6/lhq+s+KaHTd2MKGol37k7NKEv7eMe9xfxdb6V/BEW8DczG6UXeDFDc0LHY36tNH+7ddH93CDDS5OfTSvy6z+A5qLMGc/ItSp8u7U1l1A4iDhEzRVXkHeJ/23tawUUYkjQOAL/KUGaoywVcjI6z+yP0ofppTM0X2uhkVgUy8yc3U7wBiiyZZPAHEPFlfqsLAgJErX/2V+Qzy3sh6lU8Hviop8D0R8Lpf68Bk+mNZf/HFpW6xcni+iLomeMu9C8tOyn9HVgLoJbic0NAahWPzbyi7u5nLPfU1nlqaEolgjTxHg/ZA5KCjwgPMVwHavFgOex0MzCJPwDCTBVjZuYfTjD31ILxZYAodXKBisYmTdq+faLVyl7/jx+09LCbyOZblOOkuOlYqIcO3mQSzdODva0M9Tjt+LiutIFMB9mfF0xPc/494tLk2B77duHU06HDfoINmHeJfIYbTA4raUB1nQJBxbX07ZQDAh/KljPJQIDZEsM7StUoziyEYqSU2Qae9KVHy6C4rk1qjFIzWCZfy0xjOmeEYnzNz6Z6SS0cz12mPiTc5zkj8lfZCX9pTLBB7uOigta6e5qZn/jE+frk
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
